### ISSUE TITLE
Learning Rate 조절

### ISSUE THREAD

**Issue by krikit** [ecarg/grace#58]
현재 CNN 모델의 경우 학습을 진행할 수록 f-score가 떨어집니다. 고정된 epoch 수 만큼 반복적으로 학습을 진행하는 것이 아니라, learning rate를 줄이거나 학습을 중단하는 조건을 줄 수 있도록 수정합니다.

**Comment by hubert-lee** [comment]
learning rate를 좀 더 효과적으로 적용해보기 위해서 최대 성능 모델부터 다시 학습 할 수 있도록
save_checkpoint 기능도 함께 구현 되었습니다.

**Comment by krikit** [comment]
--rvt-epoch 옵션 만큼 연속으로 epoch을 도는 동안 f-score 최대치를 경신하지 못하면 기존 최대치로 모델을 revert하고 learning rate에 0.9를 곱합니다. (기본값 2 epoch)

--rvt-term (termination) 옵션 만큼 연속으로 revert를 했는데 f-score 최대치를 경신하지 못하면 학습을 종료합니다. (기본값 10 revert)

**Comment by krikit** [comment]
* one more thing
  - 위 방법으로 revert 횟수를 모두 소진하면서 learning rate를 낮춰도 최대치를 경신하지 못하면,
  - learning rate를 10배 늘인 다음 위 방법을 한번 더 시도하여 local maxima를 탈출을 시도해 해봅니다.
  - 10배로 늘린 후에는 learning rate에 0.8을 곱합니다.

두번째로 revert termination 조건에 도달하면 종료하도록 합니다.

learning rate 추이
```
revert | learning rate
---------------------
1      | 0.900000
2      | 0.810000
3      | 0.729000
4      | 0.656100
5      | 0.590490
6      | 0.531441
7      | 0.478297
8      | 0.430467
9      | 0.387420
10     | 0.348678
0      | 10.0000        <= one more thing
1      | 8.00000
2      | 6.40000
3      | 5.12000
4      | 4.09600
5      | 3.27680
6      | 2.62144
7      | 2.09715
8      | 1.67772
9      | 1.34218
10     | 1.07374
```
