### ISSUE TITLE
형태소 태그 임베딩 자질 추가

### ISSUE THREAD

**Issue by krikit** [ecarg/grace#72]
형태소 분석기를 붙여서 음절 별 출력 값을 그대로 임베딩으로 사용하도록 자질을 추가합니다.

**Comment by hubert-lee** [comment]
형태소 분석 후 생성되는 결과는 음절당 625차원의 벡터입니다.
이것을 50차원짜리 음절 임베딩 뒤에 붙여서 사용했을 경우 파라메터의 수가 많아져서
전체적으로 속도가 저하되고, 성능도 제대로 나오지 않는 부정적인 영향이 있습니다.

이것을 보완하기 위해서 소프트 맥스 후, 음절 당 결정되는 태그 하나를 대상으로 임베딩을 따로 부여하여
사용하도록 변경합니다.
